GET http://localhost:3001

###
POST http://localhost:3001/api/add-todo
Content-Type: application/json

{
    "text":"Learn Apps"
}

###
PUT http://localhost:3001/api/todos/67f74c40128ee630c992b11d
Content-Type: application/json

{
    "text":"Learn Java",
    "isChecked":true
}

###
GET http://localhost:3001/api/todos

###

POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"Veeru",
    "email":"Veeru@gmail.com",
    "password":"Veeru@2025"
}

###
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "email":"Veeru@gmail.com",
    "password":"Veeru@2025"
}
